### DISCUSSION TITLE
Any way to install through Ansible?

### DISCUSSION THREAD

**Discussion by romanpeters** [unifi-utilities/unifi-common#381] [Q&A] [answered]
I like to do all my provisioning through Ansible, but I can't get the installation steps to work.
The task hangs on running `unifi-os`, and I haven't found a way to send commands into the unifi-os shell.

This is my Ansible task so far:
```
--- 
- name: Install UDM utilities
  hosts: all
  
  tasks:
    - name: download on-boot script
      get_url:
        url: https://raw.githubusercontent.com/boostchicken-dev/udm-utilities/HEAD/on-boot-script/remote_install.sh
        dest: /tmp/remote_install.sh
        
    - name: force install on-boot script
      shell:
        cmd: cat /tmp/remote_install.sh | /bin/sh
        
    - name: enter unifi-os # this step doesn't work, since it keeps waiting for it to complete
      shell:
        cmd: unifi-os shell
        
    - name: download udm-boot package
      get_url:
        url: https://udm-boot.boostchicken.dev
        dest: /tmp/udm-boot.deb
        
    - name: install udm-boot package
      apt:
        deb: /tmp/udm-boot.deb
```
